services:
    app:
        container_name: laravel_app
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - "8000:80"
        volumes:
            - .:/var/www/html
        depends_on:
            - db
        working_dir: /var/www/html
        networks:
            - laravel

    db:
        image: postgres:13
        container_name: pg_db
        restart: always
        ports:
            - "5432:5432"
        environment:
            POSTGRES_DB: laravel
            POSTGRES_USER: laravel
            POSTGRES_PASSWORD: secret
        volumes:
            - db_data:/var/lib/postgresql/data
        networks:
            - laravel

networks:
    laravel:

volumes:
    db_data:
